#!/bin/bash
#
# insta485run
#
# Clean, build and start server
#
# Andrew DeOrio <awdeorio@umich.edu>

# Stop on errors, print commands
set -e
set -x

# Set up environment for Flask debug server
export FLASK_DEBUG=True
export FLASK_APP=REST_Example

# Run development server
flask run --host 0.0.0.0 --port 8000
